### ISSUE TITLE
homework/1.6.1 Часы

### ISSUE THREAD

**Issue by sautin1** [Nifhelm/1c-front-end#1]
Привет! Молодец, что разобрался с заданием!
Есть несколько замечаний:
1) секундная стрелка должна быть красного цвета;
2) !!!отступы!!! И зачем эти переносы запятых на следующую строчку? Выглядит же ужасно :(
3) \* Чтобы не получались такие длинные функции, как твоя Chasi, лучше разбивать ее на несколько более мелких логически законченных функций. Например, в этом случае можно было написать такие отдельные функции:
- по функции на отрисовку каждой из стрелочек;
- функция, рисующая засечки;
и вызвать их из Chasi.

__
\* пункты со звездочкой - это требования, не обязательные для сдачи задания, но очень желательные для твоего саморазвития как программиста.

**Comment by sautin1** [comment]
Написал тебе несколько замечаний в коде. :)

**Comment by Nifhelm** [comment]
Я писал через Brackets что бы был под рукой Life Preview, но думал более менее исправил отступы..(Просто там был пакет Beautify, который помогал мне код видеть красивым..)
Удалены лишние переменные ;
Убрал перенос запятых ;

**Comment by sautin1** [comment]
Написал еще :)

**Comment by sautin1** [comment]
https://github.com/Nifhelm/1c-front-end/commit/76217ec0fab9e765a973499b52f3b96ffea66c6c
напоминаю, что тут все еще лежат некоторые замечания по часам :)

**Comment by Nifhelm** [comment]
Исправил

**Comment by sautin1** [comment]
Отлично! Задачи принята, молодец! :)
